---
- name: "configuration play"
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:
    - name: Copy the bash script to the EC2 instance
      copy:
        src: ./scripts/setup-ec2.sh
        dest: /tmp/setup-ec2.sh
        remote_src: yes
        mode: '0755'

    - name: Run the bash script to configure the EC2 server
      shell: |
        /tmp/setup-ec2.sh
